/**
 * ZK-TLS Notary proof verification (Vlayer)
 * 
 * Verifies ZK-TLS Notary proofs generated by Vlayer.
 * Vlayer is currently the only supported ZK-TLS Notary provider.
 */

import type { ZkTlsNotaryProofData } from '../types/proof.js';
import { FetchHttpClient, type HttpClient } from '../types/common.js';

/**
 * Verification result from Vlayer ZK-TLS Notary proof verification
 */
export interface ZkTlsNotaryVerificationResult {
  /** Whether verification succeeded */
  success: boolean;
  /** The server domain that was proven */
  serverDomain: string;
  /** The notary key fingerprint */
  notaryKeyFingerprint: string;
  /** The proven response data (what was extracted from the TLS session) */
  responseData: unknown;
  /** Error message if verification failed */
  error?: string;
}

/** Options for verifying a ZK-TLS Notary proof */
export interface VerifyZkTlsNotaryOptions {
  /** Vlayer client ID */
  clientId: string;
  /** Vlayer auth token */
  authToken: string;
  /** Optional custom HTTP client (defaults to FetchHttpClient) */
  httpClient?: HttpClient;
}

/**
 * Verify a Vlayer ZK-TLS Notary proof by calling the Vlayer verification endpoint
 * 
 * @param proof - The ZK-TLS Notary proof data (Vlayer format)
 * @param expectedData - Optional expected data to compare against (for strict validation)
 * @param options - Authentication credentials and optional HTTP client
 * @returns Verification result
 */
export async function verifyZkTlsNotaryProof(
  proof: ZkTlsNotaryProofData,
  expectedData?: unknown,
  options?: VerifyZkTlsNotaryOptions,
): Promise<ZkTlsNotaryVerificationResult> {
  try {
    if (!options?.authToken) {
      return {
        success: false,
        serverDomain: proof.serverDomain,
        notaryKeyFingerprint: proof.notaryKeyFingerprint,
        responseData: null,
        error: 'Vlayer authToken is required',
      };
    }

    const httpClient = options.httpClient ?? new FetchHttpClient();

    // v2: single bearer header, no x-client-id
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${options.authToken}`,
    };

    // vlayer v2 is strict on the request body and rejects unknown fields with
    // INVALID_REQUEST. Legacy IPFS-stored proofs may carry extras like `success`
    // alongside `data`/`version`/`meta` — keep only the accepted keys.
    const p = proof.proof as { data: string; version: string; meta: { notaryUrl: string }; [k: string]: unknown };
    const minimalProof = {
      data: p.data,
      version: p.version,
      meta: { notaryUrl: p.meta?.notaryUrl },
    };

    const response = await httpClient.post(
      proof.verificationEndpoint,
      JSON.stringify(minimalProof),
      headers,
    );

    if (response.status < 200 || response.status >= 300) {
      return {
        success: false,
        serverDomain: proof.serverDomain,
        notaryKeyFingerprint: proof.notaryKeyFingerprint,
        responseData: null,
        error: `Vlayer verification endpoint returned status ${response.status}`,
      };
    }

    const wire = JSON.parse(response.body) as any;

    // v2: { apiVersion, success, data, error? } — unwrap; tolerate unwrapped (defensive)
    if (!wire.success) {
      const code = wire.error?.code ?? 'UNKNOWN';
      const msg = wire.error?.message ?? wire.error ?? 'Vlayer verification failed';
      return {
        success: false,
        serverDomain: proof.serverDomain,
        notaryKeyFingerprint: proof.notaryKeyFingerprint,
        responseData: null,
        error: `${code}: ${msg}`,
      };
    }
    const result = wire.data ?? wire;

    // Validate against expected data if provided
    // Compare only the fields present in expectedData against the vlayer result.
    // This ensures that non-deterministic provider metadata (e.g. traceId) that
    // may be added to the response over time does not cause false verification failures.
    if (expectedData !== undefined) {
      // Create canonical JSON strings for comparison (sorted keys recursively)
      // This ensures field order doesn't affect the comparison
      const canonicalize = (obj: any): any => {
        if (obj === null || obj === undefined || typeof obj !== 'object') {
          return obj;
        }

        if (Array.isArray(obj)) {
          return obj.map(canonicalize);
        }

        // Sort keys and recursively canonicalize values
        const sorted: any = {};
        for (const key of Object.keys(obj).sort()) {
          sorted[key] = canonicalize(obj[key]);
        }
        return sorted;
      };

      // Project source object to only include keys present in the expected shape.
      // Extra keys in the source (e.g. traceId) are dropped so they don't affect comparison.
      const projectToExpectedKeys = (source: any, expected: any): any => {
        if (expected === null || expected === undefined || typeof expected !== 'object') {
          return source;
        }
        if (Array.isArray(expected)) {
          if (!Array.isArray(source)) return source;
          return source.map((item: any, i: number) =>
            i < expected.length ? projectToExpectedKeys(item, expected[i]) : item
          );
        }
        const projected: any = {};
        for (const key of Object.keys(expected)) {
          if (key in source) {
            projected[key] = projectToExpectedKeys(source[key], expected[key]);
          }
        }
        return projected;
      };

      const projectedResult = projectToExpectedKeys(result, expectedData);
      const canonicalResult = JSON.stringify(canonicalize(projectedResult));
      const canonicalExpected = JSON.stringify(canonicalize(expectedData));
      const dataMatch = canonicalResult === canonicalExpected;

      if (!dataMatch) {
        return {
          success: false,
          serverDomain: result.serverDomain || proof.serverDomain,
          notaryKeyFingerprint: result.notaryKeyFingerprint || proof.notaryKeyFingerprint,
          responseData: result,
          error: 'Verified data does not match expected data',
        };
      }
    }

    // Extract the response data from Vlayer result for return value
    const responseData = result.response?.body 
      ? (typeof result.response.body === 'string' 
          ? JSON.parse(result.response.body) 
          : result.response.body)
      : null;

    return {
      success: true,
      serverDomain: result.serverDomain || proof.serverDomain,
      notaryKeyFingerprint: result.notaryKeyFingerprint || proof.notaryKeyFingerprint,
      responseData,
    };
  } catch (error) {
    return {
      success: false,
      serverDomain: proof.serverDomain,
      notaryKeyFingerprint: proof.notaryKeyFingerprint,
      responseData: null,
      error: error instanceof Error ? error.message : 'Unknown verification error',
    };
  }
}

/**
 * Create a ZK-TLS Notary proof for Vlayer
 * 
 * @param options - Proof creation options
 * @returns ZK-TLS Notary proof data
 */
export function createVlayerProof(options: {
  /** The raw proof data from Vlayer */
  proofData: {
    data: string;
    version: string;
    meta: {
      notaryUrl: string;
    };
  };
  /** Server domain that was proven */
  serverDomain: string;
  /** Notary public key fingerprint */
  notaryKeyFingerprint: string;
  /** Optional custom verification endpoint (defaults to Vlayer's) */
  verificationEndpoint?: string;
}): ZkTlsNotaryProofData {
  return {
    trustModel: 'mathematical',
    mechanism: 'zk_tls_notary',
    platform: 'vlayer',
    proof: options.proofData,
    verificationEndpoint: options.verificationEndpoint || 'https://web-prover.production.vlayer.xyz/api/v2.0/verify',
    serverDomain: options.serverDomain,
    notaryKeyFingerprint: options.notaryKeyFingerprint,
  };
}
